// Re-export the app-generated Payload types so seed entries are validated against the
// real Payload schema at compile time (a schema change the seed hasn't
// followed fails `typecheck` via the `satisfies` on each entry).
export type {
  Home,
  About,
  Research,
  Service,
  Hr,
  Contact,
  Navigation,
  SiteSetting,
  BlogIndex,
  ProductIndex,
  Category,
  Credential,
  Post,
  Product,
  Page,
  Tag,
  // Type-only relative ref into the app's generated types (gitignored,
  // regenerated by `payload generate:types`). Type-only, so it is erased at
  // build — no runtime coupling between the packages.
} from '../../app/src/payload-types';

import type {BasePayload as PayloadApi} from 'payload';
// Resolve Payload's generated module augmentation during standalone package typechecks; this import is erased.
type SeedPayloadTypecheck = PayloadApi;

import type {Locale} from './locales';

export type GlobalSlug =
  | 'home'
  | 'about'
  | 'blogIndex'
  | 'productIndex'
  | 'research'
  | 'service'
  | 'hr'
  | 'contact'
  | 'navigation'
  | 'siteSettings';

export type CollectionSlug =
  | 'users'
  | 'media'
  | 'categories'
  | 'credentials'
  | 'tags'
  | 'posts'
  | 'products'
  | 'pages';

// Per-locale values: the default locale (zh-hans) is required, en is optional —
// Payload's fallback covers untranslated reads, so authoring English is left as
// editorial work (out of scope here).
export type Localized<T> = {'zh-hans': T} & Partial<Record<Locale, T>>;

type WithMarkdownContent<T> = T extends {content?: infer V}
  ? Omit<T, 'content'> & {content?: V | string | null}
  : T;

type WithMarkdownBody<T> = T extends {body?: infer V}
  ? Omit<T, 'body'> & {body?: V | string | null}
  : T;

export type Authoring<T> = WithMarkdownBody<WithMarkdownContent<T>>;

/**
 * A seed entry for a Payload global. Seed values are written only when the
 * target is uninitialized; Payload remains the runtime authority after boot.
 *
 * `shared` holds non-localized/identity fields written once; `locales` holds the
 * localized editorial copy written per locale. Use `satisfies GlobalEntry<Home>`
 * etc. so the entry is checked against the generated Payload shape.
 */
export interface GlobalEntry<T> {
  kind: 'global';
  slug: GlobalSlug;
  refs?: EntryRefs;
  shared?: Partial<Authoring<T>>;
  locales: Localized<Partial<Authoring<T>>>;
}

export type EntryRefs = Record<
  string,
  | {collection: CollectionSlug; key: string}
  | {collection: CollectionSlug; key: string; field: string}
  | {collection: CollectionSlug; keys: string[]}
  | {collection: CollectionSlug; keys: string[]; field: string}
>;

/** As GlobalEntry, but for a collection document created by its stable `slug`. */
export interface CollectionEntry<T> {
  kind: 'collection';
  slug: CollectionSlug;
  /** Stable seed key — the document slug. */
  key: string;
  /**
   * Relationship fields resolved by slug at write time: field name → target
   * collection + the referenced docs' slugs. The engine resolves each slug to an
   * id and merges the id array into the written data. Non-localized — resolved
   * once per entry, not per locale. A slug that resolves to no doc is a hard
   * error, never a silently dropped relation; and the referenced docs must seed
   * earlier in the registry than this entry (resolution reads the DB).
   */
  refs?: EntryRefs;
  shared?: Partial<Authoring<T>>;
  locales: Localized<Partial<Authoring<T>>>;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AnyEntry = GlobalEntry<any> | CollectionEntry<any>;
